---
env:
  browser: true
ignorePatterns:
  # copy from other libraries
  - oauth/oauth.js
  # build from plugins_source
  - plugins/autocomplete.js
  # out-of-date
  - plugins/outputz.js
  - plugins/related_results.js
  - plugins/search2.js
  - plugins/stream_search.js
  - plugins/worldcup-2010.js
globals: # defined at lang.js
  langList: readonly
  langNames: readonly
  langResources: readonly
overrides:
- files: lang.js
  globals:
    langNames: off
    langList: off
    langResources: off
- files: plugins/*.js
  globals: # defined at twicli.js
    "$": readonly
    _: readonly
    callPlugins: readonly
    closeRep: readonly
    confirm_close: readonly
    cookieVer: readonly
    cumulativeOffset: readonly
    decr_enter: readonly
    default_api_args_tl: readonly
    deleteCookie: readonly
    deleteStatus: readonly
    dispReply: readonly
    dispReply2: readonly
    display_as_rt: readonly
    enqueuePost: readonly
    ent: readonly
    error: readonly
    fav: readonly
    fav_mode: writable
    footer: writable
    getTwMaxId: readonly
    get_next_func: writable
    hashtag_pattern: readonly
    hrefStatus: readonly
    last_user: readonly
    link: readonly
    loadXDomainScript: readonly
    max_count: readonly
    max_count_u: readonly
    myid: readonly
    myname: readonly
    nextButton: readonly
    no_counter: readonly
    no_resize_fst: readonly
    no_since_id: readonly
    nr_limit: readonly
    pluginstr: readonly
    popup_ele: readonly
    popup_hide: readonly
    popup_id: readonly
    popup_top: readonly
    popup_user: readonly
    press: readonly
    quoteStatus: readonly
    readCookie: readonly
    registerPlugin: readonly
    removeScheme: readonly
    rep_top: writable
    rep_trace_id: writable
    replies_in_tl: readonly
    replyTo: readonly
    retweetStatus: readonly
    scrollToDiv: readonly
    selected_menu: readonly
    seq: writable
    since_id: readonly
    since_id_reply: readonly
    switchDirect: readonly
    switchMisc: readonly
    switchReply: readonly
    switchTL: readonly
    switchTo: readonly
    switchUser: readonly
    switchUserTL: readonly
    text: readonly
    toDate: readonly
    twShow2: readonly
    twShowToNode: readonly
    twitterAPI: readonly
    twitterURL: readonly
    updateInterval: readonly
    user_picks: writable
    writeCookie: readonly
    xds: readonly
- files:
  - ./*.js
  - oauth/*.js
  - plugins/*.js
  extends: eslint:recommended
  rules:
    no-empty:
      - error
      - allowEmptyCatch: true
    no-mixed-spaces-and-tabs:
      - error
      - smart-tabs
    no-redeclare: off
    no-unused-vars:
      - error
      - vars: local
- files:
  - ./twicli.js
  - oauth/consumer.js
  globals:
    OAuth: readonly # defined at oauth/oauth.js
    consumer: readonly # defined at oauth/consumer.js
    hex_sha1: readonly # defined by oauth/sha1.js
  rules:
    no-constant-condition: off # for IE
- files:
  - oauth/consumer.js
  globals:
    OAuth: readonly # defined at oauth/oauth.js
    consumer: off
- files:
  - plugins/debug.js
  globals:
    auto_update: readonly # obsolated parameter
- files:
  - plugins/find_rt.js
  rules:
    no-constant-condition:
      - error
      - checkLoops: false
- files:
  - plugins/lists.js
  - plugins/mute.js
  globals:
    setRegexp: readonly # defined at plugins/regexp.js
    pickup_regexp: readonly # defined at plugins/regexp.js
    pickup_regexp_ex: writable # defined at plugins/regexp.js
- files:
  - plugins/multi_account.js
  rules:
    no-self-assign: off
- files:
  - plugins/move2https.js
  rules:
    no-inner-declarations: off
- files:
  - plugins/notify_desktop.js
  env:
    amd: true
    commonjs: true
  globals:
    Notify: readonly # defined by itself
  rules:
    no-unused-vars: off
    no-prototype-builtins: off
- files:
  - plugins/resolve_url.js
  globals:
    replaceUrl: readonly # defined by itself
  rules:
    no-prototype-builtins: off
- files:
  - plugins/shortcutkey.js
  globals:
    addIDRegexp: readonly # defined at plugins/regexp.js
    translateStatus: readonly # defined at plugins/translate.js
- files:
  - plugins/tweets_after_rt.js
  globals:
    twFavPlugin: readonly # defined at plugins/favotter.js
- files:
  - plugins/thumbnail.js
  globals:
    thumbnail_plugin: writable # defined by itself
  rules:
    no-cond-assign: off
- files: plugins_source/**/*.js
  env:
    es6: true
    node: true
