name: ESLint
on: [push]
jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: yarn global add eslint
      name: Install ESLint
    - run: $(yarn global bin)/eslint .
      name: Run ESLint
